spring:
  data:
    mongodb:
      uri: mongodb://adityapadole2001_db_user:ksSFnstvV3ZhhGta@ac-i9hndwa-shard-00-00.xrqbvyh.mongodb.net:27017,ac-i9hndwa-shard-00-01.xrqbvyh.mongodb.net:27017,ac-i9hndwa-shard-00-02.xrqbvyh.mongodb.net:27017/journaldb?tls=true&replicaSet=atlas-eb6x8n-shard-0&authSource=admin&retryWrites=true&w=majority&tlsInsecure=true
      database: journaldb
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      timeout: 5000

  kafka:
    bootstrap-servers: pkc-619z3.us-east1.gcp.confluent.cloud:9092
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: "org.apache.kafka.common.security.plain.PlainLoginModule required username='MBTMMOPBCD4CLHX7' password='cfltGZtnhVdX27tW1rbpiWCZsbZqFyl52hMHnetuHBDuJNIoI6UD5gxDHev4Ar+A';"
      session:
        timeout:
          ms: 45000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # This tells Kafka to convert your SentimentData object to JSON
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  # FIXED: Moved mail inside 'spring'
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# FIXED: Moved client.id outside or under spring.kafka
client:
  id: ccloud-springboot-client-842e46fa-c68d-4e6f-96c9-92ebc851c1dd

weather:
  api:
    key: ${WEATHER_API_KEY}

logging:
  level:
    com.unemployment.journalapplication: DEBUG # Use lowercase if you renamed packages!
    org.springframework.data.mongodb: INFO
    org.springframework.security: DEBUG
    org.springframework.data.mongodb.core: DEBUG